# Generated by Django 4.1.2 on 2023-11-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_usermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='pic',
            field=models.CharField(default='', max_length=100),
        ),
    ]
